import { saveResource, deleteResource } from "@/lib/admin/actions";
import { resourceFor, type Field } from "@/lib/admin/resources";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import { DeleteButton } from "@/components/admin/delete-button";
import { MediaPicker } from "@/components/admin/media-picker";

function inputValue(value: unknown) { if (value === null || value === undefined) return ""; if (typeof value === "boolean") return undefined; if (typeof value === "number") return String(value); return String(value); }
function FieldInput({ field, value, media }: { field: Field; value: unknown; media: { id: string; title: string | null; alt_text: string | null; category: string | null; rights_status: string; width: number | null; height: number | null; bucket: string; storage_path: string }[] }) { const common = { name: field.key, required: field.required, defaultValue: inputValue(value), className: "mt-1 block w-full border border-[#c9bfa8] bg-white px-3 py-2 text-sm" }; if (field.type === "checkbox") return <label className="flex items-center gap-2 text-sm"><input name={field.key} type="checkbox" defaultChecked={value === true} />{field.label}</label>; if (field.type === "textarea") return <label className="block text-sm">{field.label}<textarea {...common} rows={4} /></label>; if (field.type === "media") return <label className="block text-sm">{field.label}<MediaPicker name={field.key} value={inputValue(value)} media={media} /></label>; if (field.type === "select") return <label className="block text-sm">{field.label}<select {...common}>{field.options?.map((option: string) => <option value={option} key={option}>{option}</option>)}</select></label>; return <label className="block text-sm">{field.label}<input {...common} type={field.type ?? "text"} /></label>; }
export default async function AdminResourcePage({ params }: { params: Promise<{ resource: string }> }) { const { resource: key } = await params; const resource = resourceFor(key); if (!resource) notFound(); const supabase = await createServerSupabaseClient(); const [result, mediaResult] = await Promise.all([supabase.from(resource.table).select("*").order(resource.fields.some((field) => field.key === "sort_order") ? "sort_order" : "created_at", { ascending: true }), supabase.from("media").select("id,title,alt_text,category,rights_status,width,height,bucket,storage_path").eq("rights_status", "approved").order("created_at", { ascending: false })]); const media = (mediaResult.data ?? []) as { id: string; title: string | null; alt_text: string | null; category: string | null; rights_status: string; width: number | null; height: number | null; bucket: string; storage_path: string }[]; const rows = (result.data ?? []) as unknown as Record<string, unknown>[]; return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-[#b26043]">CMS module</p><h1 className="mt-3 font-serif text-5xl">{resource.label}</h1></div><p className="text-sm text-[#596052]">{rows.length} record{rows.length === 1 ? "" : "s"}</p></div><div className="mt-10 grid gap-8 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="grid gap-4">{rows.map((row) => <details className="border border-[#c9bfa8] bg-[#ede3d0] p-5" key={String(row.id)}><summary className="cursor-pointer font-serif text-2xl">{String(row.title ?? row.name ?? row.site_name ?? row.page_key ?? row.author_name ?? row.id)}</summary><form action={saveResource} className="mt-6 grid gap-4"><input type="hidden" name="resource" value={resource.key} /><input type="hidden" name="id" value={String(row.id)} />{resource.fields.map((field) => <FieldInput field={field} value={row[field.key]} media={media} key={field.key} />)}<div className="flex gap-3"><button className="bg-[#1f3426] px-4 py-2 text-sm font-semibold text-white" type="submit">Save changes</button></div></form><form action={deleteResource} className="mt-3"><input type="hidden" name="resource" value={resource.key} /><input type="hidden" name="id" value={String(row.id)} /><DeleteButton>Delete record</DeleteButton></form></details>)}</div><form action={saveResource} className="h-fit grid gap-4 border border-[#c9bfa8] bg-[#e8dfca] p-6"><h2 className="font-serif text-3xl">Add {resource.label}</h2><input type="hidden" name="resource" value={resource.key} />{resource.fields.map((field) => <FieldInput field={field} key={field.key} value={undefined} media={media} />)}<button className="bg-[#b65d40] px-4 py-3 text-sm font-semibold text-white" type="submit">Create record</button></form></div></section>; }
