import type { Metadata } from "next";
import { PageHero } from "@/components/public/page-hero";
import { PublicShell } from "@/components/public/public-shell";
import { CtaLink } from "@/components/ui/cta";
import { publicVisit } from "@/lib/public-data/queries";
import { seoMetadata } from "@/lib/public-data/seo";
export const dynamic = "force-dynamic";
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export async function generateMetadata(): Promise<Metadata> { return seoMetadata("visit", "Visit", "Plan your visit to Chatten Cafe.", "/visit"); }
export default async function VisitPage() { const { contact, hours, socials } = await publicVisit(); return <PublicShell socials={socials}><PageHero eyebrow="Plan your visit" title="Come for the view. Stay for the story." description="Everything available for planning a relaxed visit to Chatten." /><div className="py-20"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-12"><section><h2 className="font-serif text-4xl">Find Chatten</h2><p className="mt-6 max-w-xl text-lg leading-8 text-ink">{contact?.address ?? "Address and directions are being prepared."}</p><div className="mt-8 flex flex-wrap gap-3">{contact?.directions_url ? <CtaLink href={contact.directions_url} target="_blank" rel="noreferrer">Get Directions</CtaLink> : null}{contact?.whatsapp_url ? <CtaLink variant="outline" href={contact.whatsapp_url} target="_blank" rel="noreferrer">Chat on WhatsApp</CtaLink> : null}{contact?.phone ? <CtaLink variant="outline" href={`tel:${contact.phone.replace(/\s/g, "")}`}>Call Chatten</CtaLink> : null}{contact?.email ? <CtaLink variant="outline" href={`mailto:${contact.email}`}>Email Chatten</CtaLink> : null}</div>{contact?.map_embed_url ? <div className="mt-10 aspect-video bg-line-soft"><iframe className="h-full w-full border-0" title="Chatten map" src={contact.map_embed_url} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div> : null}</section><section className="bg-sand p-7"><h2 className="font-serif text-4xl">Opening hours</h2><dl className="mt-8 grid gap-3">{hours.length ? hours.map((hour) => <div className="flex justify-between border-b border-line-deep pb-3 text-sm" key={hour.day_of_week}><dt>{days[hour.day_of_week]}</dt><dd>{hour.is_closed ? "Closed" : `${hour.opens_at?.slice(0, 5) ?? "—"} – ${hour.closes_at?.slice(0, 5) ?? "—"}`}</dd></div>) : <p className="text-ink">Hours coming soon.</p>}</dl></section></div></div></PublicShell>; }
