import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const event=fs.readFileSync("lib/admin/event-actions.ts","utf8");
const promotion=fs.readFileSync("lib/admin/promotion-actions.ts","utf8");
const manager=fs.readFileSync("components/admin/event-promotion-manager.tsx","utf8");
test("event schema mapping exposes real fields and safe save",()=>{for(const field of ["title","slug","summary","body","image_media_id","starts_at","ends_at","is_active","status"])assert.match(event,new RegExp(field));assert.match(event,/requireAdmin/);assert.match(event,/rights_status/);assert.match(event,/from\("events"\)/);assert.match(event,/sort_order/); assert.match(event,/reorderEvents/); assert.match(event,/setEventActive/); assert.match(event,/deleteEvent/);});
test("promotion schema mapping exposes real fields and safe save",()=>{for(const field of ["title","slug","summary","body","image_media_id","starts_at","ends_at","is_active","status"])assert.match(promotion,new RegExp(field));assert.match(promotion,/requireAdmin/);assert.match(promotion,/rights_status/);assert.match(promotion,/from\("promotions"\)/);assert.match(promotion,/sort_order/); assert.match(promotion,/reorderPromotions/); assert.match(promotion,/setPromotionActive/); assert.match(promotion,/deletePromotion/);});
test("event temporal validation rejects reversed dates",()=>{assert.match(event,/Event end must be after its start/);assert.match(event,/starts_at.*required/);});
test("promotion temporal fields remain optional and ordered",()=>{assert.match(promotion,/Promotion end must be after its start/);assert.match(promotion,/startsAt&&endsAt/);});
test("shared picker initializes current media for both managers",()=>{assert.match(manager,/MediaPicker name="image_media_id" value=\{row.image_media_id\?\?undefined\}/);assert.match(manager,/rights_status/);});
test("operational controls preserve media and normalize order",()=>{assert.match(fs.readFileSync("components/admin/event-promotion-manager.tsx","utf8"),/Media asset remains preserved/);assert.match(event,/normalize/);assert.match(promotion,/normalize/);});
