import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const event=fs.readFileSync("lib/admin/event-actions.ts","utf8");
const promotion=fs.readFileSync("lib/admin/promotion-actions.ts","utf8");
const manager=fs.readFileSync("components/admin/event-promotion-manager.tsx","utf8");
test("event schema mapping exposes real fields and safe save",()=>{for(const field of ["title","slug","summary","body","image_media_id","starts_at","ends_at","is_active","status"])assert.match(event,new RegExp(field));assert.match(event,/requireAdmin/);assert.ok(!/rights_status/.test(event),"the event action gates on rights_status again");assert.match(event,/from\("events"\)/);assert.doesNotMatch(event,/sort_order|reorderEvents/); assert.match(event,/setEventActive/); assert.match(event,/deleteEvent/);});
test("promotion schema mapping exposes real fields and safe save",()=>{for(const field of ["title","slug","summary","body","image_media_id","starts_at","ends_at","is_active","status"])assert.match(promotion,new RegExp(field));assert.match(promotion,/requireAdmin/);assert.ok(!/rights_status/.test(promotion),"the promotion action gates on rights_status again");assert.match(promotion,/from\("promotions"\)/);assert.doesNotMatch(promotion,/sort_order|reorderPromotions/); assert.match(promotion,/setPromotionActive/); assert.match(promotion,/deletePromotion/);});
// A82: the two actions used to carry their own date parser and their own
// English range message. Both now go through the shared helpers, so the
// contract is "starts_at is required and the range is asserted", not the exact
// wording — assertRange owns the sentence and form-schema.test.mjs pins it.
test("event temporal validation rejects reversed dates",()=>{assert.match(event,/parseTimestamp\(formData\.get\("starts_at"\), "Waktu mulai event", \{ required: true \}\)/);assert.match(event,/parseTimestamp\(formData\.get\("ends_at"\), "Waktu selesai event"\)/);assert.match(event,/assertRange\(startsAt, endsAt, "event"\)/);assert.doesNotMatch(event,/new Date\(/,"the event action parses dates itself again instead of using parseTimestamp");});
test("promotion temporal fields remain optional and ordered",()=>{assert.match(promotion,/parseTimestamp\(formData\.get\("starts_at"\), "Waktu mulai promo"\)/);assert.match(promotion,/parseTimestamp\(formData\.get\("ends_at"\), "Waktu selesai promo"\)/);assert.doesNotMatch(promotion,/required: true/,"a promotion date became mandatory; both columns are nullable");assert.match(promotion,/assertRange\(startsAt, endsAt, "promo"\)/);});
test("shared picker initializes current media for both managers",()=>{assert.match(manager,/MediaPicker name="image_media_id" value=\{row.image_media_id\?\?undefined\}/);assert.ok(!/rights_status/.test(manager),"the shared manager narrows the picker by rights_status again");});
test("operational controls preserve media without ordering dependency",()=>{assert.match(fs.readFileSync("components/admin/event-promotion-manager.tsx","utf8"),/Berkas media tetap disimpan/);assert.doesNotMatch(fs.readFileSync("components/admin/event-promotion-manager.tsx","utf8"),/SortableList|Move Up|Move Down|display order/);});
test("public ordering contracts remain temporal",()=>{const queries=fs.readFileSync("lib/public-data/queries.ts","utf8");const homepage=fs.readFileSync("lib/homepage/data.ts","utf8");assert.match(queries,/public(Visible)?Rows<PublicEvent>\("events", "starts_at"\)/);assert.ok(homepage.includes('rows(supabase, "promotions", "created_at")') && homepage.includes('rows(supabase, "events", "starts_at")'));});
