import type { Metadata } from "next";
import { MediaImage } from "@/components/public/media-image";
import { PageHero } from "@/components/public/page-hero";
import { PublicShell } from "@/components/public/public-shell";
import { publicMedia, publicMenu } from "@/lib/public-data/queries";
import { seoMetadata } from "@/lib/public-data/seo";
export const dynamic = "force-dynamic";
export async function generateMetadata(): Promise<Metadata> { return seoMetadata("menu", "Menu", "Explore Chatten Cafe coffee, tea, and kitchen selections.", "/menu"); }
export default async function MenuPage() { const [{ items, categories }, media] = await Promise.all([publicMenu(), publicMedia()]); return <PublicShell><PageHero eyebrow="From the kitchen & bar" title="Take your time with the menu." description="A selection for early starts, slow afternoons, and evenings that last a little longer." /><main className="py-20"><div className="mx-auto max-w-7xl px-6 lg:px-12">{categories.map((category) => { const group = items.filter((item) => item.category_id === category.id); if (!group.length) return null; return <section className="mb-20" key={category.id}><h2 className="font-serif text-4xl">{category.name}</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{group.map((item) => <article className="bg-[#e8dfca] p-5" key={item.id}><MediaImage media={media[item.image_media_id ?? ""]} alt="" sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" className="h-52" /><h3 className="mt-5 font-serif text-2xl">{item.name}</h3>{item.description ? <p className="mt-2 text-sm leading-6 text-[#4d5649]">{item.description}</p> : null}{item.price && item.price > 0 ? <p className="mt-4 text-sm font-semibold">{new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(item.price)}</p> : null}</article>)}</div></section>; })}{!items.length ? <p className="text-[#4d5649]">The menu is being refreshed. Please check back soon.</p> : null}</div></main></PublicShell>; }
