import Link from "next/link";
import { Suspense } from "react";
import { AdminMobileNav, AdminSidebar, type NavGroup } from "@/components/admin/admin-nav";
import { SavedNotice } from "@/components/admin/saved-notice";
import { SubmitButton } from "@/components/admin/submit-button";
import { requireAdmin } from "@/lib/auth/require-admin";
import { signOut } from "@/lib/admin/actions";
const groups: readonly NavGroup[] = [["Website", [["Homepage", "/admin/homepage"], ["Hero", "/admin/hero"], ["Chatten Moments", "/admin/moments"], ["Menu", "/admin/menu"], ["Experiences", "/admin/experiences"], ["Spaces", "/admin/spaces"], ["Gallery", "/admin/gallery"], ["Events", "/admin/events"], ["Promotions", "/admin/promotions"], ["About", "/admin/about"], ["Visit Chatten", "/admin/contact"], ["Preview", "/admin/preview"]]], ["Content", [["Media Library", "/admin/media"], ["Testimonials", "/admin/testimonials"], ["Navigation", "/admin/navigation"]]], ["Settings", [["Website Settings", "/admin/site-settings"], ["Opening Hours", "/admin/opening-hours"], ["Contact & Location", "/admin/contact"], ["Social Media", "/admin/social"], ["SEO", "/admin/seo"]]]] as const;
export const dynamic = "force-dynamic";
export default async function AdminLayout({ children }: Readonly<{ children: React.ReactNode }>) { const user=await requireAdmin(); const isAdmin = user.cmsRole === "admin" || user.cmsRole === "super_admin"; return <div className="min-h-screen bg-[#f7f5f0] text-[#1f2c22]"><AdminSidebar groups={groups} isAdmin={isAdmin}/><div className="lg:pl-64"><header className="sticky top-0 z-20 flex min-h-16 items-center justify-between gap-3 border-b border-[#dde0d7] bg-[#f7f5f0]/95 px-5 lg:px-8"><div className="flex items-center gap-3"><AdminMobileNav groups={groups} isAdmin={isAdmin}/><Link href="/admin" className="font-serif text-lg lg:hidden">CHATTEN CMS</Link></div><p className="hidden text-sm text-[#657064] lg:block">Manage website content with confidence.</p><div className="flex items-center gap-3"><span className="hidden text-xs text-[#657064] sm:block">{user.email}</span><form action={signOut}><SubmitButton className="rounded border border-[#1f3426] px-3 py-1.5 text-xs font-semibold" pendingLabel="Signing out…">Sign out</SubmitButton></form></div></header><main className="mx-auto max-w-[1500px] p-5 lg:p-8"><Suspense fallback={null}><SavedNotice/></Suspense>{children}</main></div></div>; }
