import { notFound } from "next/navigation";
import Link from "next/link";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { MediaPicker } from "@/components/admin/media-picker";
import { saveMenuItem } from "@/lib/admin/menu-actions";
import { UnsavedChangesGuard } from "@/components/admin/unsaved-changes-guard";
export const dynamic="force-dynamic";
export default async function EditMenuItem({params}:{params:Promise<{id:string}>}){const {id}=await params;const supabase=await createServerSupabaseClient();const [{data:itemRaw},{data:categories},{data:media}]=await Promise.all([supabase.from("menu_items").select("*").eq("id",id).maybeSingle(),supabase.from("menu_categories").select("*").order("sort_order"),supabase.from("media").select("id,title,alt_text,category,width,height,bucket,storage_path")]);const item=itemRaw as any; if(!item)notFound();return <section className="max-w-2xl"><Link href="/admin/menu" className="text-sm underline">← Back to menu</Link><h1 className="mt-4 font-serif text-3xl sm:text-4xl lg:text-5xl">Edit menu item</h1><form action={saveMenuItem} className="mt-8 rounded border bg-white p-6"><UnsavedChangesGuard/><input type="hidden" name="id" value={String(item.id)}/><label className="block text-sm">Name<input name="name" required defaultValue={String(item.name)} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="mt-4 block text-sm">Category<select name="category_id" defaultValue={String(item.category_id)} className="mt-1 w-full rounded border px-3 py-2">{((categories??[]) as any[]).map((category:any)=><option key={String(category.id)} value={String(category.id)}>{String(category.name)}</option>)}</select></label><label className="mt-4 block text-sm">Slug<input name="slug" required defaultValue={String(item.slug)} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="mt-4 block text-sm">Price<input name="price" required defaultValue={String(item.price??"")} className="mt-1 w-full rounded border px-3 py-2"/></label><label className="mt-4 block text-sm">Description<textarea name="description" defaultValue={String(item.description??"")} className="mt-1 w-full rounded border px-3 py-2"/></label><MediaPicker name="image_media_id" value={item.image_media_id?String(item.image_media_id):undefined} media={(media??[]) as never[]}/><label className="mt-4 flex gap-2 text-sm"><input name="is_active" type="checkbox" defaultChecked={Boolean(item.is_active)}/>Available</label><input type="hidden" name="status" value={String(item.status)}/><button className="mt-6 rounded bg-forest px-5 py-3 text-sm font-semibold text-white">Save changes</button></form></section>}


