"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth/require-admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
const uuidPattern=/^[0-9a-f-]{36}$/i;
function slugifyEvent(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function parseEventDate(value:string,field:string,required=false){const trimmed=value.trim();if(!trimmed){if(required)throw new Error(`${field} is required.`);return null}const date=new Date(trimmed);if(Number.isNaN(date.getTime()))throw new Error(`Invalid ${field.toLowerCase()}.`);return date.toISOString()}
function refresh(){revalidatePath("/admin/events");revalidatePath("/events");revalidatePath("/")}
export async function saveEvent(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");const title=String(formData.get("title")??"").trim();const slug=slugifyEvent(String(formData.get("slug")??title));const summary=String(formData.get("summary")??"").trim()||null;const body=String(formData.get("body")??"").trim()||null;const startsAt=parseEventDate(String(formData.get("starts_at")??""),"Event start",true);const endsAt=parseEventDate(String(formData.get("ends_at")??""),"Event end");if(!title)throw new Error("Event title is required.");if(!slug)throw new Error("Event slug is required.");if(startsAt&&endsAt&&new Date(endsAt)<new Date(startsAt))throw new Error("Event end must be after its start.");const imageMediaId=String(formData.get("image_media_id")??"")||null;const status=String(formData.get("status")??"draft");if(!["draft","published"].includes(status))throw new Error("Invalid event status.");const supabase=await createServerSupabaseClient();if(imageMediaId){const {data,error}=await supabase.from("media").select("rights_status").eq("id",imageMediaId).maybeSingle();if(error||data?.rights_status!=="approved")throw new Error("Event image must be an approved media item.")}const payload={title,slug,summary,body,image_media_id:imageMediaId,starts_at:startsAt,ends_at:endsAt,is_active:formData.get("is_active")==="on",status};const result=id?await supabase.from("events").update(payload).eq("id",id):await supabase.from("events").insert(payload);if(result.error)throw new Error("Unable to save event.");refresh();redirect("/admin/events?saved=1")}
export async function setEventActive(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");if(!uuidPattern.test(id))throw new Error("Invalid event ID.");const supabase=await createServerSupabaseClient();const {error}=await supabase.from("events").update({is_active:String(formData.get("active"))==="true"}).eq("id",id);if(error)throw new Error("Unable to update event visibility.");refresh()}
export async function deleteEvent(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");if(!uuidPattern.test(id))throw new Error("Invalid event ID.");const supabase=await createServerSupabaseClient();const {error}=await supabase.from("events").delete().eq("id",id);if(error)throw new Error("Unable to delete event.");refresh()}
