"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/require-admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { applyOrder } from "@/lib/admin/reorder";
import { parseStatus, uuidSchema } from "@/lib/admin/form-schema";
export async function reorderGalleryItems(ids:string[]){await requireAdmin();if(!ids.length)throw new Error("The new Gallery order was not received. Reload the page and try reordering again.");const supabase=await createServerSupabaseClient();const {data,error}=await supabase.from("gallery_items").select("id").in("id",ids);if(error||data?.length!==ids.length)throw new Error("One of the reordered Gallery items no longer exists. Reload the page to see the current list.");await applyOrder("gallery_items", ids, 0, "Gallery order");revalidatePath("/admin/gallery");revalidatePath("/gallery");}
// Alt text is optional: an operator who leaves it blank gets the caption, and
// failing that the media row's own alt text, rather than a rejected save. The
// image itself is still required — a gallery tile with no image is nothing.
export async function saveGalleryItem(formData:FormData){await requireAdmin();const supabase=await createServerSupabaseClient();const id=String(formData.get("id")??"");const title=String(formData.get("title")??"").trim()||null;const payload={title,alt_text:String(formData.get("alt_text")??"").trim()||title,image_media_id:String(formData.get("image_media_id")??"")||null,is_active:formData.get("is_active")==="on",status:parseStatus(formData.get("status"))};if(!payload.image_media_id||!uuidSchema.safeParse(payload.image_media_id).success)throw new Error("Choose an image for this Gallery item.");const result=id?await supabase.from("gallery_items").update(payload).eq("id",id):await supabase.from("gallery_items").insert({...payload,sort_order:Number(((await supabase.from("gallery_items").select("sort_order").order("sort_order",{ascending:false}).limit(1).maybeSingle()).data as {sort_order:number}|null)?.sort_order??-1)+1});if(result.error)throw new Error("Unable to save Gallery item.");revalidatePath("/admin/gallery");revalidatePath("/gallery");}
export async function deleteGalleryItem(formData:FormData){await requireAdmin();const {error}=await (await createServerSupabaseClient()).from("gallery_items").delete().eq("id",String(formData.get("id")));if(error)throw new Error("Unable to remove Gallery item.");revalidatePath("/admin/gallery");revalidatePath("/gallery");}
export async function toggleGalleryItem(formData:FormData){await requireAdmin();const {error}=await (await createServerSupabaseClient()).from("gallery_items").update({is_active:String(formData.get("active"))==="true"}).eq("id",String(formData.get("id")));if(error)throw new Error("Unable to update visibility.");revalidatePath("/admin/gallery");revalidatePath("/gallery");}

