"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/require-admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { applyOrder } from "@/lib/admin/reorder";
import { parseStatus, uuidSchema } from "@/lib/admin/form-schema";
export async function reorderGalleryItems(ids:string[]){await requireAdmin();if(!ids.length)throw new Error("Invalid Gallery order.");const supabase=await createServerSupabaseClient();const {data,error}=await supabase.from("gallery_items").select("id").in("id",ids);if(error||data?.length!==ids.length)throw new Error("Unknown Gallery item.");await applyOrder("gallery_items", ids, 0, "Gallery order");revalidatePath("/admin/gallery");revalidatePath("/gallery");}
export async function saveGalleryItem(formData:FormData){await requireAdmin();const supabase=await createServerSupabaseClient();const id=String(formData.get("id")??"");const payload={title:String(formData.get("title")??"").trim()||null,alt_text:String(formData.get("alt_text")??"").trim(),image_media_id:String(formData.get("image_media_id")??"")||null,is_active:formData.get("is_active")==="on",status:parseStatus(formData.get("status"))};if(!payload.alt_text||!payload.image_media_id||!uuidSchema.safeParse(payload.image_media_id).success)throw new Error("Approved image and alt text are required.");const mediaCheck=await supabase.from("media").select("id").eq("id",payload.image_media_id).eq("rights_status","approved").maybeSingle();if(mediaCheck.error||!mediaCheck.data)throw new Error("Selected image is not approved.");const result=id?await supabase.from("gallery_items").update(payload).eq("id",id):await supabase.from("gallery_items").insert({...payload,sort_order:Number(((await supabase.from("gallery_items").select("sort_order").order("sort_order",{ascending:false}).limit(1).maybeSingle()).data as {sort_order:number}|null)?.sort_order??-1)+1});if(result.error)throw new Error("Unable to save Gallery item.");revalidatePath("/admin/gallery");revalidatePath("/gallery");}
export async function deleteGalleryItem(formData:FormData){await requireAdmin();const {error}=await (await createServerSupabaseClient()).from("gallery_items").delete().eq("id",String(formData.get("id")));if(error)throw new Error("Unable to remove Gallery item.");revalidatePath("/admin/gallery");revalidatePath("/gallery");}
export async function toggleGalleryItem(formData:FormData){await requireAdmin();const {error}=await (await createServerSupabaseClient()).from("gallery_items").update({is_active:String(formData.get("active"))==="true"}).eq("id",String(formData.get("id")));if(error)throw new Error("Unable to update visibility.");revalidatePath("/admin/gallery");revalidatePath("/gallery");}

