"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/require-admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { applyOrder } from "@/lib/admin/reorder";

export async function toggleHomepageSection(formData: FormData) { await requireAdmin(); const id=String(formData.get("id") ?? ""); const visible=String(formData.get("visible")) === "true"; const supabase=await createServerSupabaseClient(); const {error}=await supabase.from("homepage_sections").update({is_visible:visible}).eq("id",id); if(error) throw new Error("Unable to update homepage section."); revalidatePath("/"); revalidatePath("/admin/homepage"); }
export async function moveHomepageSection(formData: FormData) { await requireAdmin(); const id=String(formData.get("id") ?? ""); const direction=String(formData.get("direction")); const supabase=await createServerSupabaseClient(); const {data:rows,error}=await supabase.from("homepage_sections").select("id,sort_order").order("sort_order"); if(error) throw new Error("Unable to load homepage order."); const ordered=(rows??[]) as {id:string;sort_order:number}[]; const current=ordered.findIndex(row=>row.id===id); const target=direction === "up" ? current-1 : current+1; if(current < 0 || target < 0 || target >= ordered.length) return; const changes=await Promise.all([supabase.from("homepage_sections").update({sort_order:ordered[target].sort_order}).eq("id",ordered[current].id),supabase.from("homepage_sections").update({sort_order:ordered[current].sort_order}).eq("id",ordered[target].id)]); if(changes.some(change=>change.error)) throw new Error("Unable to save homepage order."); revalidatePath("/"); revalidatePath("/admin/homepage"); }

export async function reorderHomepageSections(ids: string[]) { await requireAdmin(); const allowed = new Set(['hero','moments','about','menu','spaces','experiences','feature','gallery','testimonials','visit']); if (!ids.length) throw new Error('Invalid homepage order.'); const supabase = await createServerSupabaseClient(); const { data, error } = await supabase.from('homepage_sections').select('id,section_key').in('id', ids); if (error || data?.length !== ids.length || data.some((row) => !allowed.has(String(row.section_key)))) throw new Error('Unknown homepage section.'); await applyOrder('homepage_sections', ids, 0, 'homepage order'); revalidatePath('/'); revalidatePath('/admin/homepage'); }


