"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/require-admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { parseIdr } from "@/lib/menu/price";
function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
async function saveOrder(table:"menu_categories"|"menu_items", ids:string[], categoryId?:string){await requireAdmin();if(!ids.length||ids.some(id=>!/^[0-9a-f-]{36}$/i.test(id)))throw new Error("Invalid order.");const supabase=await createServerSupabaseClient();let query=supabase.from(table).select("id,sort_order").in("id",ids);if(categoryId)query=query.eq("category_id",categoryId);const {data,error}=await query;if(error||data?.length!==ids.length)throw new Error("Unknown menu records.");const temp=await Promise.all(ids.map((id,index)=>supabase.from(table).update({sort_order:100000+index}).eq("id",id)));if(temp.some(result=>result.error))throw new Error("Unable to save order.");const done=await Promise.all(ids.map((id,index)=>supabase.from(table).update({sort_order:index}).eq("id",id)));if(done.some(result=>result.error))throw new Error("Unable to save order.");revalidatePath("/admin/menu");revalidatePath("/menu");revalidatePath("/");}
export async function reorderMenuCategories(ids:string[]){await saveOrder("menu_categories",ids);}
export async function reorderMenuItems(categoryId:string,ids:string[]){await saveOrder("menu_items",ids,categoryId);}
export async function saveMenuCategory(formData:FormData){await requireAdmin();const name=String(formData.get("name")??"").trim();const id=String(formData.get("id")??"");if(!name)throw new Error("Category name is required.");const supabase=await createServerSupabaseClient();const slug=slugify(String(formData.get("slug")??name));if(!slug)throw new Error("Category slug is required.");const payload={name,slug,description:String(formData.get("description")??"").trim()||null,is_active:formData.get("is_active")==="on"};const result=id?await supabase.from("menu_categories").update(payload).eq("id",id):await supabase.from("menu_categories").insert({...payload,sort_order:Number(((await supabase.from("menu_categories").select("sort_order").order("sort_order",{ascending:false}).limit(1).maybeSingle()).data as {sort_order:number}|null)?.sort_order ?? -1)+1});if(result.error)throw new Error("Unable to save category.");revalidatePath("/admin/menu");revalidatePath("/menu");}
export async function deleteMenuCategory(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");const supabase=await createServerSupabaseClient();const {count}=await supabase.from("menu_items").select("id",{count:"exact",head:true}).eq("category_id",id);if(count){throw new Error(`Move or delete the ${count} menu items in this category before deleting it.`);}const {error}=await supabase.from("menu_categories").delete().eq("id",id);if(error)throw new Error("Unable to delete category.");revalidatePath("/admin/menu");revalidatePath("/menu");}
export async function saveMenuItem(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");const name=String(formData.get("name")??"").trim();const category_id=String(formData.get("category_id")??"");const price=parseIdr(String(formData.get("price")??""));const slug=slugify(String(formData.get("slug")??name));if(!name||!category_id||!slug||price===null)throw new Error("Name, category, slug, and valid price are required.");const supabase=await createServerSupabaseClient();const payload={category_id,name,slug,description:String(formData.get("description")??"").trim()||null,price,image_media_id:String(formData.get("image_media_id")??"")||null,is_active:formData.get("is_active")==="on",status:String(formData.get("status")??"draft")};const result=id?await supabase.from("menu_items").update(payload).eq("id",id):await supabase.from("menu_items").insert({...payload,sort_order:Number(((await supabase.from("menu_items").select("sort_order").eq("category_id",category_id).order("sort_order",{ascending:false}).limit(1).maybeSingle()).data as {sort_order:number}|null)?.sort_order ?? -1)+1});if(result.error)throw new Error("Unable to save menu item.");revalidatePath("/admin/menu");revalidatePath("/menu");revalidatePath("/");}
export async function duplicateMenuItem(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");const supabase=await createServerSupabaseClient();const {data,error}=await supabase.from("menu_items").select("category_id,name,slug,description,price,image_media_id,sort_order").eq("id",id).maybeSingle();if(error||!data)throw new Error("Menu item not found.");const copy={...data,name:`${data.name} Copy`,slug:`${data.slug}-copy-${Date.now()}`,is_active:false,status:"draft"};const result=await supabase.from("menu_items").insert(copy);if(result.error)throw new Error("Unable to duplicate menu item.");revalidatePath("/admin/menu");}
export async function deleteMenuItem(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");const {error}=await (await createServerSupabaseClient()).from("menu_items").delete().eq("id",id);if(error)throw new Error("Unable to delete menu item.");revalidatePath("/admin/menu");revalidatePath("/menu");revalidatePath("/");}
export async function toggleMenuItem(formData:FormData){await requireAdmin();const id=String(formData.get("id"));const active=String(formData.get("active"))==="true";const {error}=await (await createServerSupabaseClient()).from("menu_items").update({is_active:active}).eq("id",id);if(error)throw new Error("Unable to update availability.");revalidatePath("/admin/menu");revalidatePath("/menu");revalidatePath("/");}

