"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth/require-admin";
import { createServerSupabaseClient } from "@/lib/supabase/server";
const uuidPattern=/^[0-9a-f-]{36}$/i;
function slugifyPromotion(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function parsePromotionDate(value:string,field:string){const trimmed=value.trim();if(!trimmed)return null;const date=new Date(trimmed);if(Number.isNaN(date.getTime()))throw new Error(`Invalid ${field.toLowerCase()}.`);return date.toISOString()}
async function nextOrder(){const supabase=await createServerSupabaseClient();const {data}=await supabase.from("promotions").select("sort_order").order("sort_order",{ascending:false}).limit(1).maybeSingle();return Number((data as {sort_order:number}|null)?.sort_order??-1)+1}
async function normalize(){const supabase=await createServerSupabaseClient();const {data,error}=await supabase.from("promotions").select("id").order("sort_order").order("created_at");if(error)throw new Error("Unable to normalize promotion order.");for(const [index,row] of (data??[]).entries()){const result=await supabase.from("promotions").update({sort_order:index}).eq("id",String(row.id));if(result.error)throw new Error("Unable to normalize promotion order.")}}
function refresh(){revalidatePath("/admin/promotions");revalidatePath("/")}
export async function savePromotion(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");const title=String(formData.get("title")??"").trim();const slug=slugifyPromotion(String(formData.get("slug")??title));const summary=String(formData.get("summary")??"").trim()||null;const body=String(formData.get("body")??"").trim()||null;const startsAt=parsePromotionDate(String(formData.get("starts_at")??""),"Promotion start");const endsAt=parsePromotionDate(String(formData.get("ends_at")??""),"Promotion end");if(!title)throw new Error("Promotion title is required.");if(!slug)throw new Error("Promotion slug is required.");if(startsAt&&endsAt&&new Date(endsAt)<new Date(startsAt))throw new Error("Promotion end must be after its start.");const imageMediaId=String(formData.get("image_media_id")??"")||null;const status=String(formData.get("status")??"draft");if(!["draft","published"].includes(status))throw new Error("Invalid promotion status.");const supabase=await createServerSupabaseClient();if(imageMediaId){const {data,error}=await supabase.from("media").select("rights_status").eq("id",imageMediaId).maybeSingle();if(error||data?.rights_status!=="approved")throw new Error("Promotion image must be an approved media item.")}const payload={title,slug,summary,body,image_media_id:imageMediaId,starts_at:startsAt,ends_at:endsAt,is_active:formData.get("is_active")==="on",status};const result=id?await supabase.from("promotions").update(payload).eq("id",id):await supabase.from("promotions").insert({...payload,sort_order:await nextOrder()});if(result.error)throw new Error("Unable to save promotion.");refresh();redirect("/admin/promotions?saved=1")}
export async function reorderPromotions(ids:string[]){await requireAdmin();if(!ids.length||ids.some(id=>!uuidPattern.test(id))||new Set(ids).size!==ids.length)throw new Error("Invalid promotion order.");const supabase=await createServerSupabaseClient();const {data,error}=await supabase.from("promotions").select("id");const existing=(data??[]).map(row=>String(row.id));if(error||existing.length!==ids.length||existing.some(id=>!ids.includes(id)))throw new Error("Promotion order must include every Promotion exactly once.");for(const [index,id] of ids.entries()){const staged=await supabase.from("promotions").update({sort_order:100000+index}).eq("id",id);if(staged.error)throw new Error("Unable to save promotion order.")}for(const [index,id] of ids.entries()){const saved=await supabase.from("promotions").update({sort_order:index}).eq("id",id);if(saved.error)throw new Error("Unable to save promotion order")}refresh()}
export async function setPromotionActive(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");if(!uuidPattern.test(id))throw new Error("Invalid promotion ID.");const supabase=await createServerSupabaseClient();const {error}=await supabase.from("promotions").update({is_active:String(formData.get("active"))==="true"}).eq("id",id);if(error)throw new Error("Unable to update promotion visibility.");refresh()}
export async function deletePromotion(formData:FormData){await requireAdmin();const id=String(formData.get("id")??"");if(!uuidPattern.test(id))throw new Error("Invalid promotion ID.");const supabase=await createServerSupabaseClient();const {error}=await supabase.from("promotions").delete().eq("id",id);if(error)throw new Error("Unable to delete promotion.");await normalize();refresh()}
