export type Field = { key: string; label: string; type?: "text" | "textarea" | "number" | "checkbox" | "datetime-local" | "time" | "select" | "media"; options?: string[]; required?: boolean };
export type Resource = { key: string; label: string; table: string; group?: "website" | "content" | "settings"; description?: string; primaryKey?: string; fields: Field[] };
const editorial = [{ key: "sort_order", label: "Sort order", type: "number" as const }, { key: "is_active", label: "Active", type: "checkbox" as const }, { key: "status", label: "Status", type: "select" as const, options: ["draft", "published"] }];
export const resources: Resource[] = [
  { key: "hero", label: "Hero", table: "hero_slides", fields: [{ key: "title", label: "Title", required: true }, { key: "subtitle", label: "Subtitle", type: "textarea" }, { key: "cta_label", label: "CTA label" }, { key: "cta_url", label: "CTA URL" }, { key: "image_media_id", label: "Image", type: "media" }, ...editorial] },
  { key: "moments", label: "Chatten Moments", table: "moments", fields: [{ key: "name", label: "Name", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "image_media_id", label: "Image", type: "media" }, ...editorial] },
  { key: "about", label: "About", table: "about_sections", fields: [{ key: "title", label: "Title", required: true }, { key: "body", label: "Body", type: "textarea", required: true }, { key: "image_media_id", label: "Image", type: "media" }, ...editorial] },
  { key: "experiences", label: "Experiences", table: "experiences", fields: [{ key: "name", label: "Name", required: true }, { key: "slug", label: "Slug", required: true }, { key: "description", label: "Description", type: "textarea", required: true }, { key: "image_media_id", label: "Image", type: "media" }, ...editorial] },
  { key: "spaces", label: "Spaces", table: "spaces", fields: [{ key: "name", label: "Name", required: true }, { key: "slug", label: "Slug", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "image_media_id", label: "Image", type: "media" }, ...editorial] },
  { key: "menu-categories", label: "Menu Categories", table: "menu_categories", fields: [{ key: "name", label: "Name", required: true }, { key: "slug", label: "Slug", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "sort_order", label: "Sort order", type: "number" }, { key: "is_active", label: "Active", type: "checkbox" }] },
  { key: "menu-items", label: "Menu Items", table: "menu_items", fields: [{ key: "category_id", label: "Category ID", required: true }, { key: "name", label: "Name", required: true }, { key: "slug", label: "Slug", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "price", label: "Price", type: "number" }, { key: "image_media_id", label: "Image", type: "media" }, ...editorial] },
  { key: "gallery", label: "Gallery", table: "gallery_items", fields: [{ key: "title", label: "Title" }, { key: "alt_text", label: "Alt text", required: true }, { key: "image_media_id", label: "Image", type: "media" }, ...editorial] },
  { key: "testimonials", label: "Testimonials", table: "testimonials", fields: [{ key: "author_name", label: "Author", required: true }, { key: "quote", label: "Quote", type: "textarea", required: true }, { key: "source", label: "Source" }, ...editorial] },
  { key: "promotions", label: "Promotions", table: "promotions", fields: [{ key: "title", label: "Title", required: true }, { key: "slug", label: "Slug", required: true }, { key: "summary", label: "Summary", type: "textarea" }, { key: "body", label: "Body", type: "textarea" }, { key: "image_media_id", label: "Image", type: "media" }, { key: "starts_at", label: "Starts", type: "datetime-local" }, { key: "ends_at", label: "Ends", type: "datetime-local" }, ...editorial] },
  { key: "events", label: "Events", table: "events", fields: [{ key: "title", label: "Title", required: true }, { key: "slug", label: "Slug", required: true }, { key: "summary", label: "Summary", type: "textarea" }, { key: "body", label: "Body", type: "textarea" }, { key: "image_media_id", label: "Image", type: "media" }, { key: "starts_at", label: "Starts", type: "datetime-local", required: true }, { key: "ends_at", label: "Ends", type: "datetime-local" }, ...editorial] },
  { key: "opening-hours", label: "Opening Hours", table: "opening_hours", fields: [{ key: "day_of_week", label: "Day (0 Sunday)", type: "number", required: true }, { key: "opens_at", label: "Opens", type: "time" }, { key: "closes_at", label: "Closes", type: "time" }, { key: "is_closed", label: "Closed", type: "checkbox" }, { key: "sort_order", label: "Sort order", type: "number" }] },
  { key: "contact", label: "Contact", table: "contact_information", fields: [{ key: "address", label: "Address", type: "textarea" }, { key: "phone", label: "Phone" }, { key: "whatsapp_url", label: "WhatsApp URL" }, { key: "directions_url", label: "Directions URL" }, { key: "map_embed_url", label: "Map embed URL" }, { key: "is_active", label: "Active", type: "checkbox" }] },
  { key: "social", label: "Social Media", table: "social_links", fields: [{ key: "platform", label: "Platform", required: true }, { key: "label", label: "Label" }, { key: "url", label: "URL", required: true }, { key: "sort_order", label: "Sort order", type: "number" }, { key: "is_active", label: "Active", type: "checkbox" }] },
  { key: "navigation", label: "Navigation", table: "navigation_items", fields: [{ key: "label", label: "Label", required: true }, { key: "href", label: "URL path", required: true }, { key: "sort_order", label: "Sort order", type: "number" }, { key: "is_active", label: "Active", type: "checkbox" }] },
  { key: "seo", label: "SEO", table: "seo_settings", fields: [{ key: "page_key", label: "Page key", required: true }, { key: "title", label: "SEO title" }, { key: "description", label: "SEO description", type: "textarea" }, { key: "canonical_url", label: "Canonical URL" }, { key: "robots", label: "Robots" }] },
  { key: "site-settings", label: "Site Settings", table: "site_settings", fields: [{ key: "site_name", label: "Site name", required: true }, { key: "tagline", label: "Tagline" }, { key: "description", label: "Description", type: "textarea" }, { key: "is_active", label: "Active", type: "checkbox" }] },
];
export function resourceFor(key: string) { return resources.find((resource) => resource.key === key); }
