"use client";
import Image from "next/image";
import Link from "next/link";
import { SortableList } from "@/components/admin/sortable-list";
import { MediaPicker } from "@/components/admin/media-picker";
import { deleteGalleryItem, reorderGalleryItems, saveGalleryItem, toggleGalleryItem } from "@/lib/admin/gallery-actions";
type Gallery={id:string;title:string|null;alt_text:string;image_media_id:string|null;is_active:boolean};
type Media={id:string;title:string|null;alt_text:string|null;category:string|null;rights_status:string;width:number|null;height:number|null;bucket:string;storage_path:string};
const field="mt-1 w-full rounded border px-3 py-2";
export function GalleryManagerClient({items,media,baseUrl}:{items:Gallery[];media:Media[];baseUrl:string}) { const image=(id:string|null)=>{const row=media.find(item=>item.id===id);return row?`${baseUrl}/storage/v1/object/public/${row.bucket}/${row.storage_path}`:null}; const sortable=items.map(item=>({id:item.id,label:item.title??"Untitled image",detail:<div className="mt-2 flex items-center gap-3">{image(item.image_media_id)?<Image src={image(item.image_media_id)!} alt={item.alt_text} width={120} height={80} className="h-16 w-24 rounded object-cover"/>:null}<span className="text-xs">{item.is_active?"Visible":"Hidden"}</span></div>,actions:<><Link href={`/admin/gallery/items/${item.id}`} className="rounded border px-2 py-1 text-xs">Edit</Link><form action={toggleGalleryItem}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="active" value={String(!item.is_active)}/><button className="rounded border px-2 py-1 text-xs">{item.is_active?"Hide":"Show"}</button></form><form action={deleteGalleryItem}><input type="hidden" name="id" value={item.id}/><button className="rounded border border-red-300 px-2 py-1 text-xs text-red-700" onClick={event=>{if(!confirm(`Remove ${item.title??"this image"} from Gallery?`))event.preventDefault();}}>Delete</button></form></>})); return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#9b5a42]">Website</p><h1 className="mt-2 font-serif text-5xl">Gallery</h1><p className="mt-3 max-w-2xl text-[#657064]">Curate approved visual stories for public website.</p></div><a href="#add-gallery" className="rounded bg-[#1f3426] px-4 py-2 text-sm font-semibold text-white">+ Add Images</a></div><div className="mt-8"><SortableList onSave={reorderGalleryItems} items={sortable}/></div><form id="add-gallery" action={saveGalleryItem} className="mt-8 max-w-xl rounded border bg-white p-5"><h2 className="font-semibold">Add Gallery item</h2><label className="mt-3 block text-sm">Caption<input name="title" className="mt-1 w-full rounded border px-3 py-2"/></label><label className="mt-3 block text-sm">Alt text<input name="alt_text" required className="mt-1 w-full rounded border px-3 py-2"/></label><MediaPicker name="image_media_id" media={media}/><label className="mt-3 flex gap-2 text-sm"><input name="is_active" type="checkbox" defaultChecked/>Visible</label><input type="hidden" name="status" value="published"/><button className="mt-4 rounded bg-[#1f3426] px-4 py-3 text-sm font-semibold text-white">Add to Gallery</button></form></section>; }


