import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
const allowed=new Map([["image/jpeg","jpg"],["image/png","png"],["image/webp","webp"],["image/avif","avif"]]);
function parseArgs(argv){const i=argv.indexOf("--manifest");if(i<0||!argv[i+1])throw new Error("Usage: npm run media:import -- --manifest path [--dry-run]");return{manifest:path.resolve(argv[i+1]),dryRun:argv.includes("--dry-run")};}
function detectMime(bytes){if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return"image/jpeg";if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)return"image/png";if(bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP")return"image/webp";if(bytes.toString("ascii",4,8)==="ftyp"&&bytes.toString("ascii",8,12).includes("avif"))return"image/avif";}
function dimensions(bytes,type){if(type==="image/png")return{width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};return{width:null,height:null};}
const {manifest,dryRun}=parseArgs(process.argv.slice(2));const doc=JSON.parse(await fs.readFile(manifest,"utf8"));if(!Array.isArray(doc.items))throw new Error("Manifest items must be an array.");const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Missing server runtime configuration.");const supabase=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false},db:{schema:"chatten_cafe"}});const base=path.dirname(manifest);
for(const item of doc.items){if(item.rights_status!=="approved")throw new Error(`Import rejected: ${item.key} is not approved.`);if(!item.key||!item.source||!item.title||!item.alt||!item.category)throw new Error(`Invalid manifest item: ${item.key??"unknown"}`);let bytes,filename;if(/^https:\/\//i.test(item.source)){const response=await fetch(item.source);if(!response.ok)throw new Error(`Download failed for ${item.key}: ${response.status}`);bytes=Buffer.from(await response.arrayBuffer());filename=path.basename(new URL(item.source).pathname)||`${item.key}.bin`;}else{filename=path.basename(item.source);bytes=await fs.readFile(path.resolve(base,item.source));}if(bytes.length>10*1024*1024)throw new Error(`Image too large: ${item.key}`);const type=detectMime(bytes);if(!type||!allowed.has(type))throw new Error(`Unsupported or invalid image: ${item.key}`);const hash=crypto.createHash("sha256").update(bytes).digest("hex"),dims=dimensions(bytes,type),storagePath=`site/${item.category}/${hash.slice(0,16)}-${item.key.replace(/[^a-z0-9_-]/gi,"-")}.${allowed.get(type)}`;const {data:duplicate}=await supabase.from("media").select("id,storage_path").eq("sha256",hash).maybeSingle();console.log(JSON.stringify({key:item.key,filename:storagePath,category:item.category,rights_status:item.rights_status,duplicate:Boolean(duplicate),dry_run:dryRun}));if(dryRun||duplicate)continue;const upload=await supabase.storage.from("chatten-media").upload(storagePath,bytes,{contentType:type,upsert:false});if(upload.error)throw upload.error;const {error}=await supabase.from("media").insert({bucket:"chatten-media",storage_path:storagePath,original_filename:filename,mime_type:type,file_size:bytes.length,width:dims.width,height:dims.height,alt_text:item.alt,title:item.title,source_type:item.source_type??"operator-upload",source_reference:item.source_reference??null,attribution:item.attribution??null,rights_status:item.rights_status,sha256:hash,tags:item.tags??[],category:item.category});if(error){await supabase.storage.from("chatten-media").remove([storagePath]);throw error;}}