import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { PublicShell } from "@/components/public/public-shell";
import { getHomepageData } from "@/lib/homepage/data";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { MediaImage } from "@/components/public/media-image";
import { CtaLink } from "@/components/ui/cta";
import type { Card, HomepageData, Media, Moment } from "@/lib/homepage/types";

export const dynamic = "force-dynamic";
export const revalidate = 300;

export async function generateMetadata(): Promise<Metadata> { const data = await getHomepageData(); return { title: data.settings?.site_name ?? "Chatten Cafe", description: data.settings?.description ?? "A place to eat, talk, and experience Batu." }; }

const sectionTitle = "font-serif text-4xl leading-[.95] sm:text-5xl lg:text-6xl";
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
// A42: was a CSS background, which next/image cannot size — every card and
// tile shipped its full-resolution original to a phone. `sizes` is per call
// site because a 4-up gallery tile and a full-bleed hero need very different
// candidates from the same asset.
function visual(media: Media | undefined, sizes: string, className = "", priority = false, scrim: "soft" | "strong" = "soft") { return <MediaImage media={media} sizes={sizes} alt="" scrim={scrim} className={className} priority={priority} />; }
function CardGrid({ items, media, heading }: { items: Card[]; media: HomepageData["media"]; heading: string }) { if (!items.length) return <p className="mt-8 max-w-lg text-[#4d5649]">{heading} will be curated soon.</p>; return <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.slice(0, 3).map((item) => <article key={item.id} className="group overflow-hidden bg-[#e8dfca]"><div className="h-64 overflow-hidden">{visual(media[item.image_media_id ?? ""], "(min-width: 1024px) 33vw, (min-width: 768px) 50vw, 100vw", "h-full transition-transform duration-500 group-hover:scale-[1.03]")}</div><div className="p-6"><p className="font-serif text-2xl">{item.name}</p>{item.description ? <p className="mt-3 text-sm leading-6 text-[#4d5649]">{item.description}</p> : null}</div></article>)}</div>; }
function MomentCard({ moment, media, index }: { moment: Moment; media: HomepageData["media"]; index: number }) { return <article className="relative min-h-80 overflow-hidden rounded-sm border border-white/15 p-6 text-white" key={moment.id}>{visual(media[moment.image_media_id ?? ""], "(min-width: 1280px) 25vw, (min-width: 768px) 50vw, 100vw", "absolute inset-0", false, "strong")}<div className="relative flex h-full min-h-64 flex-col justify-between"><span className="text-xs uppercase tracking-[.2em] text-[#f3c4a6]">0{index + 1}</span><div><h3 className="font-serif text-4xl">{moment.name}</h3>{moment.description ? <p className="mt-3 max-w-xs text-sm leading-6 text-white/80">{moment.description}</p> : null}</div></div></article>; }

export default async function HomePage() {
  const data = await getHomepageData(); const supabase = await createServerSupabaseClient(); const { data: configuredSections } = await supabase.from("homepage_sections").select("section_key,sort_order,is_visible").order("sort_order"); const sections = (configuredSections ?? []) as { section_key: string; sort_order: number; is_visible: boolean }[]; const sectionStyle = (key: string) => { const section = sections.find((item) => item.section_key === key); return section ? { order: section.sort_order, display: section.is_visible ? undefined : "none" } : undefined; }; const heroMedia = data.media[data.hero?.image_media_id ?? ""]; const heroTitle = data.hero?.title ?? "Datang karena pemandangannya. Pulang membawa ceritanya."; const heroText = data.hero?.subtitle ?? data.settings?.tagline ?? "A place to eat, talk, and experience Batu."; const story = data.stories[0];
  return <PublicShell navigation={data.navigation} socials={data.socials}><main id="top" className="flex flex-col overflow-x-hidden bg-[#f4eedf] text-[#1e3024]">
    <section style={sectionStyle("hero")} className="relative flex min-h-[760px] items-end bg-[#233b2a] text-white">{visual(heroMedia, "100vw", "absolute inset-0", true, "strong")}<Container className="relative z-10 pb-20 pt-44 sm:pb-28"><p className="text-xs uppercase tracking-[.26em] text-[#f3c4a6]">Chatten Cafe · Batu</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[.9] sm:text-7xl lg:text-8xl">{heroTitle}</h1><p className="mt-7 max-w-xl text-base leading-7 text-white/85 sm:text-lg">{heroText}</p><div className="mt-10 flex flex-wrap gap-3"><CtaLink href="#experience" variant="accent">Explore Chatten</CtaLink><CtaLink href="#visit" variant="onDark">Get Directions</CtaLink></div></Container></section>
    <section style={sectionStyle("moments")} id="moments" className="bg-[#1f3426] py-24 text-white"><Container><p className="text-xs uppercase tracking-[.2em] text-[#f3c4a6]">Through every hour</p><h2 className={`${sectionTitle} mt-5 max-w-xl`}>One place. Four different stories.</h2><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{data.moments.map((moment, index) => <MomentCard key={moment.id} moment={moment} media={data.media} index={index} />)}</div></Container></section>
    <section style={sectionStyle("about")} id="about" className="py-24 lg:py-32"><Container className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-[#8a3a21]">More than a table</p><h2 className={`${sectionTitle} mt-5`}>{story?.title ?? "Come for the view. Stay for the conversation."}</h2></div><div className="border-l border-[#c9bfa8] pl-6 sm:pl-10"><p className="max-w-2xl text-lg leading-8 text-[#455145]">{story?.body ?? data.settings?.description ?? "Chatten is being shaped as a destination for slow meals, long conversations, and the changing light of Batu."}</p><a className="mt-7 inline-block border-b border-[#1e3024] pb-1 text-sm font-semibold" href="#experience">Discover the Experience</a></div></Container></section>
    <section style={sectionStyle("feature")} id="experience" className="bg-[#d9c9aa] py-12 lg:py-20"><Container><div className="relative min-h-[560px] overflow-hidden bg-[#405542] p-8 text-white sm:p-12 lg:p-16">{visual(story ? data.media[story.image_media_id ?? ""] : heroMedia, "(min-width: 1280px) 1280px, 100vw", "absolute inset-0", false, "strong")}<div className="relative flex min-h-[430px] max-w-2xl flex-col justify-end"><p className="text-xs uppercase tracking-[.22em] text-[#f3c4a6]">The view is part of the table</p><h2 className={`${sectionTitle} mt-5`}>See Batu. Taste Batu. Talk more.</h2><p className="mt-6 max-w-lg leading-7 text-white/85">From first light to city lights, every visit gives the landscape a different voice.</p><CtaLink href="#visit" variant="onDark" className="mt-8 w-fit">Plan Your Visit</CtaLink></div></div></Container></section>
    <section style={sectionStyle("menu")} id="menu" className="py-24 lg:py-32"><Container><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs uppercase tracking-[.2em] text-[#8a3a21]">Taste the moment</p><h2 className={`${sectionTitle} mt-5`}>Featured from kitchen &amp; bar.</h2></div><a href="#menu" className="border-b border-[#1e3024] pb-1 text-sm font-semibold">View Full Menu</a></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{data.menu.length ? data.menu.slice(0, 4).map((item) => <article key={item.id} className="bg-[#e8dfca] p-5"><div className="h-44">{visual(data.media[item.image_media_id ?? ""], "(min-width: 1024px) 25vw, (min-width: 768px) 50vw, 100vw", "h-full")}</div><p className="mt-5 font-serif text-2xl">{item.name}</p>{item.description ? <p className="mt-2 text-sm leading-6 text-[#4d5649]">{item.description}</p> : null}{item.price && item.price > 0 ? <p className="mt-4 text-sm font-semibold">{new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(item.price)}</p> : null}</article>) : <p className="text-[#4d5649]">Menu selections will arrive soon.</p>}</div></Container></section>
    <section style={sectionStyle("spaces")} id="spaces" className="bg-[#ede3d0] py-24"><Container><p className="text-xs uppercase tracking-[.2em] text-[#8a3a21]">Find your place</p><h2 className={`${sectionTitle} mt-5`}>Spaces for every pace.</h2><CardGrid items={data.spaces} media={data.media} heading="Spaces" /></Container></section>
    <section style={sectionStyle("experiences")} className="py-24"><Container><p className="text-xs uppercase tracking-[.2em] text-[#8a3a21]">Made for memory</p><h2 className={`${sectionTitle} mt-5`}>Experiences to share.</h2><CardGrid items={data.experiences} media={data.media} heading="Experiences" /></Container></section>
    {data.feature ? <section style={sectionStyle("feature")} id="events" className="bg-[#a04e33] py-20 text-white"><Container className="grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-[#ffe8d9]">Now at Chatten</p><h2 className={`${sectionTitle} mt-5 max-w-2xl`}>{data.feature.title}</h2>{data.feature.summary ? <p className="mt-5 max-w-xl leading-7 text-white/85">{data.feature.summary}</p> : null}</div><CtaLink href="#visit" variant="onDark">Discover Event</CtaLink></Container></section> : null}
    <section style={sectionStyle("gallery")} id="gallery" className="py-24 lg:py-32"><Container><div className="flex items-end justify-between gap-6"><div><p className="text-xs uppercase tracking-[.2em] text-[#8a3a21]">A glimpse of Chatten</p><h2 className={`${sectionTitle} mt-5`}>Framed by Batu.</h2></div><a href="#gallery" className="border-b border-[#1e3024] pb-1 text-sm font-semibold">Explore Gallery</a></div>{data.gallery.length ? <div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{data.gallery.map((item, index) => <div className={`${index === 0 || index === 5 ? "md:col-span-2 md:row-span-2" : ""} min-h-48`} key={item.id}>{visual(data.media[item.image_media_id ?? ""], index === 0 || index === 5 ? "(min-width: 768px) 50vw, 50vw" : "(min-width: 768px) 25vw, 50vw", "h-full")}</div>)}</div> : <div className="mt-10 grid min-h-80 place-items-center bg-[#405542] text-center text-white"><p className="font-serif text-3xl">More views are on their way.</p></div>}</Container></section>
    {data.testimonials.length ? <section style={sectionStyle("testimonials")} className="bg-[#233b2a] py-24 text-white"><Container><p className="text-xs uppercase tracking-[.2em] text-[#f3c4a6]">Shared stories</p><div className="mt-10 grid gap-5 md:grid-cols-2">{data.testimonials.map((item) => <figure className="border-t border-white/25 pt-6" key={item.id}><blockquote className="font-serif text-3xl leading-tight">“{item.quote}”</blockquote><figcaption className="mt-6 text-sm text-white/70">{item.author_name}{item.source ? ` · ${item.source}` : ""}</figcaption></figure>)}</div></Container></section> : null}
    <section style={sectionStyle("visit")} id="visit" className="bg-[#d9c9aa] py-24"><Container className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs uppercase tracking-[.2em] text-[#8a3a21]">Visit Chatten</p><h2 className={`${sectionTitle} mt-5`}>Make a day of it.</h2><p className="mt-6 max-w-lg leading-7 text-[#4d5649]">{data.contact?.address ?? "Visit details are being prepared. Check back soon for directions and opening information."}</p><div className="mt-8 flex flex-wrap gap-3">{data.contact?.map_url ? <CtaLink href={data.contact.map_url} target="_blank" rel="noreferrer">Get Directions</CtaLink> : null}{data.contact?.whatsapp_url ? <CtaLink variant="outline" href={data.contact.whatsapp_url} target="_blank" rel="noreferrer">Chat on WhatsApp</CtaLink> : null}</div></div><div className="border-t border-[#a89778] pt-6 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><p className="text-xs uppercase tracking-[.2em] text-[#8a3a21]">Opening hours</p><dl className="mt-6 grid gap-3 text-sm">{data.hours.length ? data.hours.map((hour) => <div className="flex justify-between border-b border-[#baa988] pb-3" key={hour.day_of_week}><dt>{days[hour.day_of_week]}</dt><dd>{hour.is_closed ? "Closed" : `${hour.opens_at?.slice(0, 5) ?? "—"} – ${hour.closes_at?.slice(0, 5) ?? "—"}`}</dd></div>) : <p>Hours coming soon.</p>}</dl></div></Container></section>
  </main></PublicShell>;
}
